#!/bin/sh
#
# Copyright (C) 2022-2023 - Hal Martin (github.com/halmartin)
#
# Configure networking
#

start() {
	ifconfig lo 127.0.0.1 netmask 255.255.255.255 up
}

stop() {
	/bin/true
}

restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
