#!/bin/sh
#
# Copyright (C) 2022 - Hal Martin (github.com/halmartin)
#
# Do terrible things to the Meraki firmware on flash
#

find_mtd() {
    part=$(cat /proc/mtd | grep "$1" | awk '{print $1}')
    if [ ! -z ${part_old} ]; then
        echo $part_old
        return
    fi
}

extract_mtd() {
    TMP=$(mktemp -d)
    mtd=$(find_mtd part.old)
    offset=$(find_hdr -a /dev/$mtd)
    if [ ! -z ${mtd} ]; then
        cd $TMP && dd if=/dev/$mtd bs=1 skip=$offset | xzcat | cpio -id
    fi
}

start() {
    echo "pass"
}

stop() {
    echo "pass"
}

restart() {
    stop
    start
}

case "$1" in
  start)
      start
    ;;
  stop)
      stop
    ;;
  restart|reload)
      restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
