#!/bin/sh
#
# Copyright (C) Hal Martin (github.com/halmartin)
#
# Load kernel modules for managing the Vitesse ASIC
#

determine_board() {
    # first, try to get the board info from /etc/boardinfo
    if [ -f /etc/boardinfo ]; then
        model=$(grep MODEL /etc/boardinfo | grep -Eo "MS[234]2(0-[248]([48])?)?(P)?")
    # next, try to get the board info from the board-config partition on NAND
    else
        model=$(board_data model)
        if [ ! -f /etc/boardinfo ]; then
            # persist model in overlayfs
            echo MODEL=${model} > /etc/boardinfo
        fi
    fi

    # model was not correctly determined?! use cpuinfo instead
    if [ -z $model ]; then
        model=$(cat /proc/cpuinfo | grep 'system type' | grep -Eo 'VSC74[23][457]( Dual)?')
    fi

    # this will print a big error if we can't determine the model
    # or if we fell back to using cpuinfo
    if [ $(echo $model | grep -c -E "MS[234]2(0-[248]([48])?(P|LP|FP)?)?") -ne 1 ]; then
        echo "!!! IMPORTANT !!!"
        echo -n "Couldn't determine board model, THINGS WILL BE BROKEN. "
        echo -n "model=${model} "
        echo -n "please open an issue on github.com/halmartin/meraki-builder"
        echo -n
        echo -n "You can fix this by executing 'echo MS220-X > /etc/boardinfo && reboot'"
        echo "where X is 8/8P/24/24P/48/48LP/48FP according to your switch model"
        echo "!!! IMPORTANT !!!"
        sleep 30
    fi

    # detect the mod_dir and switch_board from boardinfo
    case "$model" in
        MS220-8|MS220-8P|VSC7425)
            mod_dir=luton26
            switch_board=MERAKI_BOARD_MS220_8
            echo 10 > /tmp/NUM_PORTS
        ;;
        MS220-24|MS220-24P|VSC7427)
            mod_dir=luton26
            switch_board=MERAKI_BOARD_MS220_24
            echo 24 > /tmp/NUM_PORTS
        ;;
        MS220-48|MS220-48P)
            mod_dir=jaguar_dual
            switch_board=MERAKI_BOARD_MS220_48
            echo 52 > /tmp/NUM_PORTS
        ;;
        MS320-24|MS320-24P|VSC7434)
            mod_dir=jaguar
            switch_board=MERAKI_BOARD_MS320_24
            echo 28 > /tmp/NUM_PORTS
        ;;
        MS320-48|MS320-48P|"VSC7434 Dual")
            mod_dir=jaguar_dual
            switch_board=MERAKI_BOARD_MS320_48
            echo 52 > /tmp/NUM_PORTS
        ;;
        MS22|MS22P)
            mod_dir=luton26
            switch_board=MERAKI_BOARD_MS22
            echo 24 > /tmp/NUM_PORTS
        ;;
        MS42|MS42P)
            mod_dir=jaguar_dual
            switch_board=MERAKI_BOARD_MS42
            echo 52 > /tmp/NUM_PORTS
        ;;
    esac

    export model
    export mod_dir
    export switch_board
}

load_modules() {
    # we have to load vtss_core first
    insmod ${MOD_PATH}/${mod_dir}/vtss_core.ko board_desc=${switch_board}
    if [ $? -ne 0 ]; then
        echo "Error inserting '${mod_dir}/vtss_core.ko board_desc=${switch_board}'" > /dev/kmsg
    else
        echo "Loaded '${mod_dir}/vtss_core.ko board_desc=${switch_board}'"
    fi
    # load the other modules
    modules="proclikefs merakiclick elts_meraki"
    for mod in $modules; do
        insmod ${MOD_PATH}/${mod}.ko
        if [ $? -ne 0 ]; then
            echo "Error inserting ${mod}.ko" > /dev/kmsg
        else
            echo "Loaded '${mod}.ko'"
        fi
        sleep 1
    done
    # vc_click is loaded last
    insmod ${MOD_PATH}/${mod_dir}/vc_click.ko
    if [ $? -ne 0 ]; then
        echo "Error inserting '${mod_dir}/vc_click.ko'" > /dev/kmsg
    else
        echo "Loaded '${mod_dir}/vc_click.ko'"
    fi
}

# copying with bs=1 is slow, calculate the maximum blocksize we can use with dd
largest_blocksize() {
    header_offset=$1
    max_size=1
    for size in $(seq 2 6); do
        if [ $(($header_offset % $((2**$size)))) -eq 0 ]; then
          max_size=$((2**$size))
        else
          break
        fi
    done
    echo $max_size
}

check_and_load() {
    KVER=$(uname -r | awk -F'-' '{print $1}')
    # check the module version
    RD_KVER=$(strings /tmp/lib/modules/${mod_dir}/vtss_core.ko | grep 'vermagic=' | awk -F'=' '{print $2}' | awk -F'-' '{print $1}')
    if [ "$RD_KVER" != "$KVER" ]; then
        echo "$part contains modules for $RD_KVER, but we booted $KVER"
        # clean up modules
        rm -rf /tmp/lib/modules
    else
        echo "Found kernel modules in $part"
        export MOD_PATH=/tmp/lib/modules
        load_modules
        # we loaded the modules, bail
        return
    fi
}

dump_modules() {
    MTD_PART=$(grep ${part} /proc/mtd | awk -F':' '{print $1}' | grep -o '[[:digit:]]*')
    MTD_SIZE=$(grep ${part} /proc/mtd | awk '{print $2}')
    if [ $(df /tmp | tail -1 | awk '{print $4}') -lt $MTD_SIZE ]; then
        # we don't have space in /tmp to dump the ${part}
        echo "Insufficient space in /tmp, using slower dumping method"
        RD_OFFSET=$(find_hdr -g /dev/mtdblock${MTD_PART})
        BLOCK_SIZE=$(largest_blocksize $RD_OFFSET)
        cd /tmp
        dd if=/dev/mtdblock${MTD_PART} bs=$BLOCK_SIZE skip=$(($RD_OFFSET/$BLOCK_SIZE)) | gzip -dc | cpio -idu lib/modules/*.ko lib/modules/${mod_dir}
        RD_KVER=$(strings /tmp/lib/modules/${mod_dir}/vtss_core.ko | grep 'vermagic=' | awk -F'=' '{print $2}' | awk -F'-' '{print $1}')
   fi
   dd if=/dev/mtdblock${MTD_PART} of=/tmp/${part}.bin bs=1M
   RD_OFFSET=$(find_hdr -g /tmp/${part}.bin)
   # no header, skip
   if [ $RD_OFFSET -lt 0 ]; then
       rm /tmp/${part}.bin
   else
       BLOCK_SIZE=$(largest_blocksize $RD_OFFSET)
       # found GZIP header, it's at RD_OFFSET
       dd if=/tmp/${part}.bin of=/tmp/initrd-${part}.gz bs=$BLOCK_SIZE skip=$(($RD_OFFSET/$BLOCK_SIZE))
       rm /tmp/${part}.bin
       # extract the kernel modules from initrd.gz
       cd /tmp && gzip -dc /tmp/initrd-${part}.gz | cpio -idu lib/modules/*.ko lib/modules/${mod_dir}
       rm /tmp/initrd-${part}.gz
   fi
}

fwcutter() {
    # check that the kernel modules exist
    if [ ! -d /lib/modules/${mod_dir} ]; then
        # deploy fwcutter!
        command -v find_hdr
        if [ $? -eq 0 ]; then
            # store current kernel version
            KVER=$(uname -r | awk -F'-' '{print $1}')
            export KVER
            # find the mtd partition
            fw_regions="part1 part2"
            for part in $fw_regions; do
                MTD_PART=$(grep ${part} /proc/mtd | awk -F':' '{print $1}' | grep -o '[[:digit:]]*')
                MTD_SIZE=$(grep ${part} /proc/mtd | awk '{print $2}')
                if [ $(df /tmp | tail -1 | awk '{print $4}') -lt $MTD_SIZE ]; then
                    # we don't have space in /tmp to dump the ${part}
                    echo "Insufficient space in /tmp, using slower dumping method"
                    RD_OFFSET=$(find_hdr -g /dev/mtdblock${MTD_PART})
                    BLOCK_SIZE=$(largest_blocksize $RD_OFFSET)
                    cd /tmp
                    dd if=/dev/mtdblock${MTD_PART} bs=$BLOCK_SIZE skip=$(($RD_OFFSET/$BLOCK_SIZE)) | gzip -dc | cpio -idu lib/modules/*.ko lib/modules/${mod_dir}
                    RD_KVER=$(strings /tmp/lib/modules/${mod_dir}/vtss_core.ko | grep 'vermagic=' | awk -F'=' '{print $2}' | awk -F'-' '{print $1}')
                fi
                dd if=/dev/mtdblock${MTD_PART} of=/tmp/${part}.bin bs=1M
                RD_OFFSET=$(find_hdr -g /tmp/${part}.bin)
                # no header, skip
                if [ $RD_OFFSET -lt 0 ]; then
                    rm /tmp/${part}.bin
                else
                    BLOCK_SIZE=$(largest_blocksize $RD_OFFSET)
                    # found GZIP header, it's at RD_OFFSET
                    dd if=/tmp/${part}.bin of=/tmp/initrd-${part}.gz bs=$BLOCK_SIZE skip=$(($RD_OFFSET/$BLOCK_SIZE))
                    rm /tmp/${part}.bin
                    # extract the kernel modules from initrd.gz
                    cd /tmp && gzip -dc /tmp/initrd-${part}.gz | cpio -idu lib/modules/*.ko lib/modules/${mod_dir}
                    rm /tmp/initrd-${part}.gz
                    # check the module version
                    RD_KVER=$(strings /tmp/lib/modules/${mod_dir}/vtss_core.ko | grep 'vermagic=' | awk -F'=' '{print $2}' | awk -F'-' '{print $1}')
                    if [ "$RD_KVER" != "$KVER" ]; then
                        echo "$part contains modules for $RD_KVER, but we booted $KVER"
                        # clean up modules
                        rm -rf /tmp/lib/modules
                    else
                        echo "Found kernel modules in $part"
                        export MOD_PATH=/tmp/lib/modules
                        load_modules
                        # we loaded the modules, bail
                        return
                    fi
                fi
            done
            echo "Couldn't find kernel modules for $KVER"
        else
            echo "Kernel modules are missing and find_hdr is not present!"
        fi
    else
        # the modules exist in squashfs
        export MOD_PATH=/lib/modules
        load_modules
    fi
}

start() {
    # figure out the switch board
    determine_board
    fwcutter
}

stop() {
    modules="vc_click elts_meraki merakiclick proclikefs vtss_core"
    for mod in $modules; do
        modprobe -r -f $mod
        if [ $? -ne 0 ]; then
            echo "Error removing '${mod}.ko'" > /dev/kmsg
            return
        fi
    done
}

restart() {
    stop
    start
}

case "$1" in
  start)
      start
    ;;
  stop)
      stop
    ;;
  restart|reload)
      restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
