#!/bin/sh
#
# Copyright (C) 2020-2022 - Hal Martin (github.com/halmartin)
#
# Mount click filesystem for managing the Vitesse ASIC
#

get_mac_addr() {
    if [ -f /bin/board_data ]; then
        /bin/board_data mac
    else
        dd if=/sys/devices/platform/i2c-gpio.1/i2c-1/1-0051/eeprom bs=6 skip=17 count=1 2>/dev/null | hexdump -C | head -1 | awk '{print $2,$3,$4,$5,$6,$7}' | tr ' ' ':' || echo 88:15:44:$(echo $RANDOM | cut -c0-2):$(echo $RANDOM | cut -c0-2):$(echo $RANDOM | cut -c0-2)
    fi
}

start() {
    if [ ! -f /etc/MERAKI_MAC ]; then
        # generate it to /tmp/, just in case the overlay mount failed
        # and /etc isn't writable
        get_mac_addr > /tmp/MERAKI_MAC
        cp /tmp/MERAKI_MAC /etc/
    else
        cp /etc/MERAKI_MAC /tmp/
    fi
    cp /etc/MERAKI_MAC /tmp/
    # extract the bottom three octets to use as IP
    # Meraki's logic, not mine
    cat /tmp/MERAKI_MAC | sed -n 's/.*:.*:.*:\([0-9A-Za-z:]*\):\([0-9A-Za-z:]*\):\([0-9A-Za-z:]*\).*/printf 6.%d.%d.%d\\\\n 0x\1 0x\2 0x\3/p' | xargs -0 sh -c > /tmp/MERAKI_IP
    cat /tmp/MERAKI_MAC | sed -n 's/\([0-9A-Za-z]*\):\([0-9A-Za-z]*\):\([0-9A-Za-z]*\):\([0-9A-Za-z]*\):\([0-9A-Za-z]*\):\([0-9A-Za-z]*\).*/printf fd0a:9b09:1f7:0:%02x%02x:%xff:fe%02x:%02x%02x $((0x\1^0x2)) 0x\2 0x\3 0x\4 0x\5 0x\6/p' | xargs -0 sh -c > /tmp/MERAKI_IP6
    # set the hostname based on the MAC address
    # Meraki does this in S10boot
    sysctl -qw kernel.hostname=$(echo m$(cat /tmp/MERAKI_MAC) | sed -e 's/://g')
    if fgrep -q click /proc/filesystems; then
        mount -t click none /click
        # restore the default click configuration
        if [ -f /etc/switch.template.gz ]; then
            if [ -f /tmp/NUM_PORTS ]; then
                NUM_PORTS=$(cat /tmp/NUM_PORTS)
            else
                # default to MS220-8P
                NUM_PORTS=10
            fi
	    # not sure about PORT_POE_MW for non-POE models :shrug:
	    # replace MTUN_IP with a link-local address to defang (not that we run mtunnel)
	    gzip -dc /etc/switch.template.gz | sed  -e 's/__MTUN_IP__/169.254.0.1/g' -e "s/__MY_MAC_ADDRESS__/$(cat /tmp/MERAKI_MAC)/g" -e "s/__NUM_SWITCHPORTS__/$NUM_PORTS/g" -e 's/__PORT_POE_MW__/30000/g'  > /click/config
        fi
    fi
}

stop() {
    /bin/true
}

restart() {
    stop
    start
}

case "$1" in
  start)
      start
    ;;
  stop)
      stop
    ;;
  restart|reload)
      restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
