#!/bin/sh
#
# Mount/create JFFS2; bind mount /etc from /config/etc
#

mount_jffs2() {
    if [ $(grep -c "/config" /proc/mounts) -eq 0 ]; then
        # handle the mtdblock number changing
        MTD_NUM=$(grep \"config\" /proc/mtd | awk -F':' '{print $1}' | grep -Eo '[0-9]{1,2}')
        mount -t jffs2 /dev/mtdblock${MTD_NUM} /config
        if [ $? -eq 0 ]; then
            # successfully mounted /config
            echo "Mounted /config"
        else
            # format /config; COULD BE DANGEROUS!
            echo "First boot, formatting /config"
            TMPDIR=$(mktemp -d)
            cp -pRv /etc $TMPDIR/
            if [ -f $TMPDIR/etc/init.d/S99persist ]; then
                # ensure persistent storage is mounted earlier on subsequent boots
                mv $TMPDIR/etc/init.d/S99persist $TMPDIR/etc/init.d/S07persist
            fi
            # suppress error output
            #mkfs.jffs2 -o /dev/mtdblock${MTD_NUM} -l -n -r ${TMPDIR}/ 2>/dev/null
            mkfs.jffs2 -o /dev/mtdblock${MTD_NUM} -l -n -X lzo -x zlib -y 40:lzo -r ${TMPDIR}/
            rm -rf $TMPDIR
            mount -t jffs2 /dev/mtdblock${MTD_NUM} /config
            # we can't call bind_mount_persist now because it will
            # screw up init. Instead create /tmp/FIRST_BOOT to indicate this is the first boot
            touch /tmp/FIRST_BOOT
        fi
    else
        echo "/config is already mounted"
    fi
}

start() {
    mount_jffs2
}

stop() {
    umount /config
}

restart() {
    stop
    start
}

case "$1" in
  start)
      start
    ;;
  stop)
      stop
    ;;
  restart|reload)
      restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
