#!/bin/sh
#
# Mount /var/db/dhcpcd to /tmp
#

start() {
	mkdir /tmp/dhcpcd
	mount -o bind /tmp/dhcpcd /var/db/dhcpcd
}

stop() {
	umount /tmp
}

restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
