#!/bin/sh
#
# Mount/create JFFS2; bind mount /etc from /config/etc
#
bind_mount_persist() {
    if [ $(grep -c "/config" /proc/mounts) -gt 0 ]; then
        # bind mount /config/bin as /usr/local/bin
        if [ -d /config/bin ]; then
            mount -o bind /config/bin /usr/local/bin
        fi
        if [ -d /config/opt && -d /opt ]; then
            mount -o bind /config/opt /opt
        fi
        # bind mount over existing /etc
        # do this last because it tends to screw up init
        if [ -d /config/etc ]; then
            mount -o bind /config/etc /etc
        fi
    fi
}

start() {
    if [ -f /config/etc/init.d/S07persist ]; then
        # source the file so we don't overwrite the current script while executing
        . /config/etc/init.d/S07persist
    fi
    bind_mount_persist
}

stop() {
    /bin/true
}

restart() {
    stop
    start
}

case "$1" in
  start)
      start
    ;;
  stop)
      stop
    ;;
  restart|reload)
      restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
