#!/bin/sh
#
# Mount /tmp as a tmpfs
#

start() {
	mount none -t tmpfs -o size=6M /tmp
}

stop() {
	umount /tmp
}

restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
