#!/bin/sh
#
# run /etc/rc.local
#

start() {
    if [ -f /etc/rc.local ]; then
        /etc/rc.local
    fi
}

stop() {
    /bin/true
}

restart() {
    stop
    start
}

case "$1" in
  start)
      start
    ;;
  stop)
      stop
    ;;
  restart|reload)
      restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
